services:
  spark-job:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark_test_container
    volumes:
      - /c/Users/Usuario/Documents/GitHub/assignment-diario-bordo/data:/app/data
    entrypoint: []
    command:
      - spark-submit
      - --packages
      - io.delta:delta-core_2.12:2.3.0
      - src/main.py
    environment:
      - PYTHONPATH=/app