services:
  spark-job:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark_test_container      
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./spark-warehouse:/app/spark-warehouse
      - ./derby:/app/derby
    entrypoint: []    
    command:
      - /bin/sh
      - -c
      - "spark-submit --packages io.delta:delta-core_2.12:2.3.0 src/main.py && pytest tests/test_data_processor.py -v"
    environment:
      - PYTHONPATH=/app