services:
  spark-job:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark_test_container      
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./spark-warehouse:/app/spark-warehouse
      - ./derby:/app/derby
    entrypoint: []
    command:
      - spark-submit
      - --packages
      - io.delta:delta-core_2.12:2.3.0
      - src/main.py
    environment:
      - PYTHONPATH=/app