version: "3.9"

services:
  spark-job:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /c/Users/Usuario/Documents/GitHub/assignment-diario-bordo/data:/app/data
    command: spark-submit --packages io.delta:delta-core_2.12:2.1.0 src/main.py
    environment:
      - PYTHONPATH=/app
