services:
  spark-job:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark_test_container
    volumes:
      # Ajustar paths para serem relativos ao container
      - ./data:/app/data
      - ./src:/app/src
      # Mapear o warehouse do Spark para um diretório persistente
      - ./spark-warehouse:/app/spark-warehouse
    entrypoint: []
    command:
      - spark-submit
      - --packages
      - io.delta:delta-core_2.12:2.3.0
      - src/main.py
    environment:
      - PYTHONPATH=/app