version: "3.9"

services:
  spark-job:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /c/Users/Usuario/Documents/GitHub/assignment-diario-bordo/data:/app/data
    command: spark-submit src/main.py
    environment:
      - PYTHONPATH=/app
